import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationWrapper from "@/shared/components/navigation/NavigationWrapper";
import QueryProvider from "@/cms/lib/providers/QueryProvider";
import { CmsProvider } from "@/cms/lib/context/CmsContext";
import LoadingView from "@/cms/components/LoadingView";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
        <CmsProvider>
          <NavigationWrapper />
          {children}
        </CmsProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
