import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Header from "@/shared/components/navigation/Header";
import QueryProvider from "@/cms/lib/providers/QueryProvider";
import { CmsProvider } from "@/cms/lib/context/CmsContext";
import { AuthProvider } from "@/shared/contexts/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <AuthProvider>
          <QueryProvider>
            <CmsProvider>
              <header>
                <Header />
              </header>
              <main>{children}</main>
            </CmsProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
